# Generated by Django 2.0.7 on 2019-11-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
