# Generated by Django 2.0.7 on 2019-11-29 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='published_date',
        ),
    ]
