# Generated by Django 2.0.7 on 2019-11-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='cover',
            field=models.ImageField(default='/Users/apple/creativeproject-cp-467197-466439/TravelNotes/media/images/default.jpeg', upload_to='images/'),
        ),
    ]
