# Generated by Django 2.0.7 on 2019-11-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='cover',
            field=models.ImageField(default='/images/default.jpeg', upload_to='images/'),
        ),
    ]
